name: Deploy Christian Fellowship Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project with environment variables
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        BIBLE_API_KEY: ${{ secrets.BIBLE_API_KEY }}
        FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        VITE_SITE_URL: ${{ secrets.VITE_SITE_URL }}
        NODE_ENV: production
      run: |
        # Create production environment file
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env.production
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env.production
        echo "BIBLE_API_KEY=${{ secrets.BIBLE_API_KEY }}" >> .env.production
        echo "FIRECRAWL_API_KEY=${{ secrets.FIRECRAWL_API_KEY }}" >> .env.production
        echo "NODE_ENV=production" >> .env.production
        
        # Run build if build script exists, otherwise prepare for static deployment
        npm run build || echo "No build script found, deploying static files"
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        commit_message: "🚀 Deploy Fellowship Website - ${{ github.event.head_commit.message }}"
        
    - name: Performance Check with Lighthouse
      if: github.ref == 'refs/heads/main'
      uses: treosh/lighthouse-ci-action@v9
      with:
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: './.github/lighthouse/lighthouserc.js'
        
  # Security and Code Quality Checks
  security-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run security audit
      run: |
        npm audit --audit-level moderate
        
    - name: Check for sensitive data
      run: |
        # Check for accidentally committed secrets
        if grep -r "sk_" . --exclude-dir=node_modules --exclude-dir=.git; then
          echo "❌ Potential API keys found in code"
          exit 1
        fi
        echo "✅ No sensitive data detected"